name: Build Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      extractorDir: ./DataExtractor
      extractorSolutionName: ScoreDataExtractor.sln
      appsDir: ./CompileScore
      appsSolutionName: CompileScore.sln
    
    strategy:
      matrix:
        buildconfig: [Debug, Release]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    
    - name: NuGet restore ${{ env.extractorSolutionName }}
      working-directory: ${{env.extractorDir}}
      run: nuget restore ${{ env.extractorSolutionName }}
    
    - name: Build Score Data Extractor
      working-directory: ${{env.extractorDir}}
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.extractorSolutionName }}
        
    - name: NuGet restore ${{ env.appsSolutionName }}
      working-directory: ${{env.appsDir}}
      run: nuget restore ${{ env.appsSolutionName }}
     
    - name: Build Compile Score VSIX
      working-directory: ${{env.appsDir}}
      run: msbuild /m /p:Configuration=${{matrix.buildconfig}} ${{ env.appsSolutionName }}
      
    - name: Upload VSIX 2019 Extension Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompileScore-VSIX2019-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX16/bin/${{matrix.buildconfig}}/CompileScore.vsix
    
    - name: Upload VSIX 2022 Extension Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompileScore-VSIX2022-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX17/bin/${{matrix.buildconfig}}/CompileScore.vsix
    
    - name: Upload App Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompileScore-App-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/WPF/bin/${{matrix.buildconfig}}/*
