name: Build Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      extractorSolution: ./DataExtractor/ScoreDataExtractor.sln
      parserSolution: ./Parser/CompileScoreParser.sln
      appsDir: ./CompileScore
      appsSolution: CompileScore.sln
      NetPlatform: net8.0-windows
    
    strategy:
      matrix:
        buildconfig: [Debug, Release]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout LLVM library
      uses: actions/checkout@v4
      with:
        repository: Viladoman/ClangArtifacts
        sparse-checkout: llvm-project
        path: External

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
       
    - name: NuGet restore Score Data Extractor
      run: nuget restore ${{ env.extractorSolution }}
       
    - name: Build Score Data Extractor
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.extractorSolution }}
        
    - name: Build Parser
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.parserSolution }}
        
    - name: NuGet restore ${{ env.appsSolutionName }}
      working-directory: ${{env.appsDir}}
      run: nuget restore ${{ env.appsSolutionName }}
     
    - name: Build Compile Score VSIX
      working-directory: ${{env.appsDir}}
      run: msbuild /m /p:Configuration=${{matrix.buildconfig}} ${{ env.appsSolutionName }}
      
    - name: Upload Extractor Artifact 1
      uses: actions/upload-artifact@v3
      with:
        name: CompileScore-Extractor-${{matrix.buildconfig}}
        path: ${{env.baseDir}}/bin/x64/${{matrix.buildconfig}}/*.exe  
        
    - name: Upload Extractor Artifact 2
      uses: actions/upload-artifact@v3
      with:
        name: CompileScore-Extractor-${{matrix.buildconfig}}
        path: ${{env.baseDir}}/bin/x64/${{matrix.buildconfig}}/*.dll  
      
    - name: Upload VSIX 2019 Extension Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CompileScore-VSIX2019-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX16/bin/${{matrix.buildconfig}}/CompileScore.vsix
    
    - name: Upload VSIX 2022 Extension Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CompileScore-VSIX2022-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/VSIX17/bin/${{matrix.buildconfig}}/CompileScore.vsix
    
    - name: Upload App Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CompileScore-App-${{matrix.buildconfig}}
        path: ${{env.appsDir}}/WPF/bin/${{matrix.buildconfig}}/${{ env.NetPlatform }}/*
