name: Release

on:
  release:
    types:
      - created

jobs:
  export:    
    runs-on: windows-latest

    env:
      extractorDir: ./DataExtractor
      extractorSolutionName: ScoreDataExtractor.sln
      appsDir: ./CompileScore
      appsSolutionName: CompileScore.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    
    - name: NuGet restore Score Data Extractor
      working-directory: ${{env.extractorDir}}
      run: nuget restore ${{ env.extractorSolutionName }}
    
    - name: Build Score Data Extractor
      working-directory: ${{env.extractorDir}}
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.extractorSolutionName }}
      
    - name: Generate Extractor Asset
      working-directory: ${{env.extractorDir}}/bin/x64/Release
      run: Compress-Archive -Path ScoreDataExtractor.exe,CppBuildInsights.dll,KernelTraceControl.dll -DestinationPath CompileScoreExtractor.zip
      
    - name: Upload Extractor Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.extractorDir}}/bin/x64/Release/CompileScoreExtractor.zip
        asset_name: CompileScoreExtractor.zip
        asset_content_type: application/zip

    - name: NuGet restore Compile Score 
      working-directory: ${{env.appsDir}}
      run: nuget restore ${{ env.appsSolutionName }}
     
    - name: Build Compile Score
      working-directory: ${{env.appsDir}}
      run: msbuild /m /p:Configuration=Release ${{ env.appsSolutionName }}
      
    - name: Upload VSIX 2019 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.appsDir}}/VSIX16/bin/Release/CompileScore.vsix
        asset_name: CompileScore_VS2019.vsix
        asset_content_type: application/zip
    
    - name: Upload VSIX 2022 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.appsDir}}/VSIX17/bin/Release/CompileScore.vsix
        asset_name: CompileScore_VS2022.vsix
        asset_content_type: application/zip
         
    - name: Generate App Asset
      working-directory: ${{env.appsDir}}/WPF/bin/Release
      run: Compress-Archive -Path CompileScore.exe -DestinationPath CompileScoreApp.zip
      
    - name: Upload App Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.appsDir}}/WPF/bin/Release/CompileScoreApp.zip
        asset_name: CompileScoreApp.zip
        asset_content_type: application/zip
